name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: redteamuser
          POSTGRES_PASSWORD: 147r258r
          POSTGRES_DB: redteam_toolkit_db
        ports:
          - 5432:5432
        
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - run: PGPASSWORD=postgres psql -U postgres -tc "SELECT 'CREATE DATABASE redteam_toolkit_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'redteam_toolkit_db')"
      - run: PGPASSWORD=postgres psql -U postgres -tc "CREATE ROLE redteamuser with SUPERUSER CREATEDB LOGIN ENCRYPTED PASSWORD '147r258r'"
      - run: PGPASSWORD=postgres psql -U postgres -tc "GRANT ALL PRIVILEGES ON DATABASE redteam_toolkit_db TO redteamuser"
      - run: PGPASSWORD=postgres psql -U postgres -tc "ALTER DATABASE redteam_toolkit_db OWNER TO redteamuser"
      
      # https://www.hacksoft.io/blog/github-actions-in-action-setting-up-django-and-postgres#resources
      - run: sudo apt-get install libpq-dev
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-bugbear
                         flake8-comprehensions isort mypy pyupgrade safety
      - run: bandit --recursive  --skip B106,B110,B404,B602,B603,B607 .
      - run: black --check . || true
      - run: codespell
      - run: flake8 . --count --select=C,E5,E9,F63,F7,F82 --max-complexity=28
                              --max-line-length=220 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88
                      --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: |
          pip install -r requirements.txt
          mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: python manage.py makemigrations
      - run: python manage.py migrate
        env:  # https://stackoverflow.com/questions/61670081
          SECRET_KEY: 96fc8cf096d12574a61caf5a93ac4c9e3abc37094144971a1a
      - run: python manage.py test
        env:  # https://stackoverflow.com/questions/61670081
          SECRET_KEY: 96fc8cf096d12574a61caf5a93ac4c9e3abc37094144971a1a
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
